name: Agence Voyage CI/CD

on:
  push:
    branches:
      - main

env:
  AGENCE_VOYAGE_BACKEND_IMAGE: ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')/app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Log into Github Packages
      run: echo ${PERSONAL_ACCESS_TOKEN} | docker login ghcr.io -u ${{ secrets.NAMESPACE }} --password-stdin
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        
    - name: Build images
      run: |
          docker build -t ${{ env.AGENCE_VOYAGE_BACKEND_IMAGE }} .

    - name: Push images
      run: |
          docker push ${{ env.AGENCE_VOYAGE_BACKEND_IMAGE }}


  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: checkout master
        uses: actions/checkout@v2

      - name: Add environment variables to .env
        run: |
          echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
          echo AGENCE_VOYAGE_BACKEND_IMAGE=${{ env.AGENCE_VOYAGE_BACKEND_IMAGE }} >> .env
          echo NAMESPACE=${{ secrets.NAMESPACE }} >> .env
          echo PERSONAL_ACCESS_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }} >> .env

      - name: Add the private SSH key to the ssh-agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-add - <<< "${{ secrets.PRIVATE_KEY }}"

      - name: Build and deploy images on Server
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          scp  -o StrictHostKeyChecking=no -r ./.env ./Dockerfile ./docker-compose.yml ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_IP_ADDRESS }}:/home/${{ secrets.REMOTE_USER }}/agence_voyage_deploy
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_IP_ADDRESS }} << 'ENDSSH'
            cd /home/${{ secrets.REMOTE_USER }}/agence_voyage_deploy
            ls -a
            source .env
            docker login ghcr.io -u $NAMESPACE -p $PERSONAL_ACCESS_TOKEN
            docker compose -f ./docker-compose.yml down
            docker rmi -f $AGENCE_VOYAGE_BACKEND_IMAGE
            docker pull $AGENCE_VOYAGE_BACKEND_IMAGE
            docker compose -f ./docker-compose.yml up -d
          ENDSSH
